### PR TITLE
Modifying key expression handling

### LINKED ISSUE #75: [Bug] KeyExpr multiple undeclaration
### Describe the bug

Declared key expressions could be undeclared twice, causing a memory error.

The bug is caused by this line https://github.com/eclipse-zenoh/zenoh-kotlin/blob/main/zenoh-kotlin/src/commonMain/kotlin/io/zenoh/jni/JNISession.kt#L182

```kotlin
    fun undeclareKeyExpr(keyExpr: KeyExpr): Result<Unit> = runCatching {
        undeclareKeyExprViaJNI(sessionPtr.get(), keyExpr.jniKeyExpr!!.ptr)
    }
```

We need to avoid being able to undeclare a key expression if it was already undeclared.

### To reproduce

Undeclare twice a key expr.

### System info

N/A

### LINKED ISSUE #88: KeyExpr finalizer
### Describe the release item

Java finalizers are [marked as deprecated](https://openjdk.org/jeps/421) and have a considerable performance impact when the garbage collector attempts to clean an object. 

Opening this issue in order to remove the `finalize` function from the `KeyExpr` class, finding an alternative to free the native key expression instance associated to it.

### PR DESCRIPTION
**Pull request by DariusIMP**
This PR addresses a series of issues caused by a design flaw of the `KeyExpr` class.

---

The previous design of the KeyExpr class made that everyone of its instances had to be associated to a native key expression through the means of a pointer in order for it to be a valid instance. This caused an overly reliance on the `finalize()` function in order to free the native pointer, which is highly impactful in cases of high frequency communication due to the fact that the finalize `function` messes with all the garbage collector's optimisations, causing the instances of key expressions to not be freed as fast as they are allocated due to incoming samples. 

This PR introduces changes on the architecture of the `KeyExpr` class that aim to fix that issue. It now relies mostly on a string representation of the key expression, stored as an attribute. We still let the user have associated a pointer to a native key expression, but only when declaring it from a session. This is useful for cases where we can anticipate a recurrent usage of a KeyExpr instance, but for those cases it will be up to the user to free the native pointer by calling `session.undeclare(keyexpr).res()`. 

Otherwise, key expressions will simply rely on the string representation to achieve its behaviour, passing the string attribute to the native layer. This is less efficient but simplifies the memory management, allowing us to purely rely on the garbage collector. Similarly and with the same goal in mind, short lived instances of key expressions that are generated from the native layer (like when receiving a Sample from a subscriber) will contain just the string representation of it (without a pointer to a native keyexpr).

Closes #88 
Closes #75

### CODE REVIEW

File: zenoh-jni/src/key_expr.rs [hunk 1]
```diff
@@ -29,22 +30,17 @@ pub(crate) unsafe extern "C" fn Java_io_zenoh_jni_JNIKeyExpr_00024Companion_tryF
...
-    };
-    let key_expr = match KeyExpr::try_from(key_expr_str) {
-        Ok(key_expr) => key_expr,
-        Err(err) => {
-            _ = Error::KeyExpr(err.to_string()).throw_on_jvm(&mut env);
-            return null();
-        }
-    };
-    Arc::into_raw(Arc::new(key_expr))
+) -> jstring {
```
Comment (Charles-Schleich) [inline zenoh-jni/src/key_expr.rs:33]: nit: `JString` vs jstring, are similarly named. 
looks like `jstring` is a `*mut _jobject`
while `JString` is a `pub struct JString<'local>(JObject<'local>);`
and a `_jobject` is an empty enum 
`pub enum _jobject {}` 

Does this function the return an empty enum ?
I want to better understand

File: zenoh-jni/src/key_expr.rs [hunk 2]
```diff
@@ -152,3 +115,74 @@ pub(crate) unsafe extern "C" fn Java_io_zenoh_jni_JNIKeyExpr_freePtrViaJNI(
...
+        ))
+    })?;
+    let key_expr = KeyExpr::try_from(key_expr_str).map_err(|err| {
+        Error::Jni(format!(
+            "Unable to create key expression from string: {}",
+            err
+        ))
+    })?;
+    Ok(key_expr)
+}
```
Comment (Charles-Schleich) [inline zenoh-jni/src/key_expr.rs:133]: nit: Could potentially be written a bit shorter and save on an alloc, 
not sure if this will have any real world performance change, 
but reviewer has not tried, just a nit, so up to OP to decide.

File: zenoh-jni/src/key_expr.rs [hunk 3]
```diff
@@ -152,3 +115,74 @@ pub(crate) unsafe extern "C" fn Java_io_zenoh_jni_JNIKeyExpr_freePtrViaJNI(
...
+
+pub(crate) fn autocanonize_key_expr(
+    env: &mut JNIEnv,
+    key_expr: &JString,
+) -> Result<KeyExpr<'static>> {
+    let key_expr_str = decode_string(env, key_expr).map_err(|err| {
+        Error::Jni(format!(
+            "Unable to get key expression string value: {}",
+            err
+        ))
```
Comment (Charles-Schleich) [inline zenoh-jni/src/key_expr.rs:143]: nit: Potential to statically define these errors somewhere, and send back references to the errors. May change performance, reviewer has not tried, up to OP to if OP wants to try.

File: zenoh-jni/src/key_expr.rs [hunk 4]
```diff
@@ -152,3 +115,74 @@ pub(crate) unsafe extern "C" fn Java_io_zenoh_jni_JNIKeyExpr_freePtrViaJNI(
...
+    key_expr_ptr: *const KeyExpr<'static>,
+) -> Result<KeyExpr<'static>> {
+    if key_expr_ptr.is_null() {
+        match decode_key_expr(env, key_expr_str) {
+            Ok(key_expr) => Ok(key_expr),
+            Err(err) => Err(Error::Jni(format!(
+                "Unable to process key expression: {}",
+                err
+            ))),
+        }
```
Comment (Charles-Schleich) [inline zenoh-jni/src/key_expr.rs:166]: improvement: 
when Mapping `Ok(x) => Ok(x)`, a nice way to reduce some lines of code is to use the `map_err` 
function as we only really want to change what the error outputs.
Example below
```rust 
decode_key_expr(env, key_expr_str)
    .map_err(|err| Error::Jni(format!("Unable to process key expression: {}", err)))
```

File: zenoh-jni/src/key_expr.rs [hunk 5]
```diff
@@ -152,3 +115,74 @@ pub(crate) unsafe extern "C" fn Java_io_zenoh_jni_JNIKeyExpr_freePtrViaJNI(
...
+    } else {
+        let key_expr = Arc::from_raw(key_expr_ptr);
+        let key_expr_clone = key_expr.deref().clone();
+        std::mem::forget(key_expr);
+        Ok(key_expr_clone)
```
Comment (Charles-Schleich) [inline zenoh-jni/src/key_expr.rs:171]: I don't quite understand what this is doing. 
is this to get rid of the Arc or Original KeyExpr ? 
but then keep a copy. I need an adult to explain this to me.

File: zenoh-jni/src/key_expr.rs [hunk 6]
```diff
@@ -152,3 +115,74 @@ pub(crate) unsafe extern "C" fn Java_io_zenoh_jni_JNIKeyExpr_freePtrViaJNI(
...
+        ))
+    })?;
+    Ok(key_expr)
+}
+
+pub(crate) unsafe fn process_key_expr(
+    env: &mut JNIEnv,
+    key_expr_str: &JString,
+    key_expr_ptr: *const KeyExpr<'static>,
+) -> Result<KeyExpr<'static>> {
```
Comment (Charles-Schleich) [inline zenoh-jni/src/key_expr.rs:158]: What process is this function doing to a KeyExpr ?
Function name is a bit ambiguous with what its achieving.

File: zenoh-jni/src/query.rs [hunk 7]
```diff
@@ -66,19 +70,27 @@ pub(crate) unsafe extern "C" fn Java_io_zenoh_jni_JNIQuery_replySuccessViaJNI(
...
+    let key_expr: KeyExpr<'static> = match process_key_expr(&mut env, &key_expr_str, key_expr_ptr) {
+        Ok(key_expr) => key_expr,
+        Err(err) => {
+            _ = err
+                .throw_on_jvm(&mut env)
+                .map_err(|err| tracing::error!("{}", err));
+            return;
+        }
+    };
+
```
Comment (Charles-Schleich) [inline zenoh-jni/src/query.rs:90]: Look into  `map_err` When ever encountering the pattern 
```rust 
match x {
    Ok(y) => y,
    Err(err) => {
    // handle error
    }
} 
```

Something like 

```rust 
x.map_err(|err| { 
    // handle error
   })
```

File: zenoh-jni/src/query.rs [hunk 8]
```diff
@@ -254,17 +266,23 @@ pub(crate) fn on_query(
...
-    let key_expr = query.key_expr().clone();
-    let key_expr_ptr = Arc::into_raw(Arc::new(key_expr));
+    let key_expr_str = match env.new_string(&query.key_expr().to_string()) {
+        Ok(key_expr_str) => key_expr_str,
+        Err(err) => Err(Error::Jni(format!(
+            "Could not create a JString through JNI for the Query key expression. {}",
+            err
+        )))?,
+    };
+
```
Comment (Charles-Schleich) [inline zenoh-jni/src/query.rs:276]: `map_err` as above

File: zenoh-jni/src/reply.rs [hunk 9]
```diff
@@ -70,15 +68,22 @@ fn on_reply_success(
...
     }?;
 
-    let key_expr_ptr = Arc::into_raw(Arc::new(sample.key_expr));
+    let key_expr_str = match env.new_string(&sample.key_expr.to_string()) {
+        Ok(key_expr_str) => key_expr_str,
+        Err(err) => Err(Error::Jni(format!(
+            "Could not create a JString through JNI for the Sample key expression. {}",
+            err
+        )))?,
+    };
```
Comment (Charles-Schleich) [inline zenoh-jni/src/reply.rs:77]: `map_err` as above

File: zenoh-jni/src/subscriber.rs [hunk 10]
```diff
@@ -130,13 +136,23 @@ pub(crate) unsafe fn declare_subscriber(
...
+                Ok(key_expr_str) => key_expr_str,
+                Err(err) => {
+                    tracing::error!(
+                        "Could not create a JString through JNI for the Sample key expression. {}",
+                        err
+                    );
+                    return;
+                }
+            };
+
```
Comment (Charles-Schleich) [inline zenoh-jni/src/subscriber.rs:149]: nit: There may be a nicer way to write all these matches that have returns, but id need to think about it

File: zenoh-jni/src/subscriber.rs [hunk 11]
```diff
@@ -148,9 +164,11 @@ pub(crate) unsafe fn declare_subscriber(
                 Ok(_) => {}
                 Err(err) => {
                     tracing::error!("On subscriber callback error: {}", err.to_string());
-                    Arc::from_raw(key_expr_ptr); // Free key expr pointer
```
Comment (Charles-Schleich) [inline zenoh-jni/src/subscriber.rs:151]: using `if let Err(err)`, avoids  `Ok(_) => {}`. 

```rust 
if let Err(err) = env.call_method(
    &callback_global_ref,
    "run",
    "(Ljava/lang/String;[BIIJZ[B)V",
    &[
        JValue::from(&key_expr_str),
        JValue::from(&byte_array),
        JValue::from(encoding),
        JValue::from(kind),
        JValue::from(timestamp as i64),
        JValue::from(is_valid),
        JValue::from(&attachment_bytes),
    ],
){
    tracing::error!("On subscriber callback error: {}", err.to_string());
}
```

File: zenoh-kotlin/src/commonTest/kotlin/io/zenoh/KeyExprTest.kt [hunk 12]
```diff
@@ -52,10 +52,10 @@ class KeyExprTest {
         assertNotEquals(keyExpr1, keyExpr3)
 
         keyExpr2.close()
-        assertNotEquals(keyExpr1, keyExpr2)
+        assertEquals(keyExpr1, keyExpr2)
 
         keyExpr1.close()
-        assertNotEquals(keyExpr1, keyExpr2)
+        assertEquals(keyExpr1, keyExpr2)
```
Comment (Charles-Schleich) [inline zenoh-kotlin/src/commonTest/kotlin/io/zenoh/KeyExprTest.kt:58]: is this logic flip intentional ?

**Review by Charles-Schleich — CHANGES_REQUESTED** [review]
Most of it is good, 
There are some stylistic and more Rusty ways of writing the Rust portion. 
I don't see anything obviously wrong with the Rust code. 

Is there a way that you can add some Rust specific tests, so that we can have some coverage ?

Note: I did not review in depth the Kotlin Part, i would get a second set of eyes with someone that has experience with Kotlin.

File: zenoh-kotlin/src/commonTest/kotlin/io/zenoh/KeyExprTest.kt (hunk 12 above)
Comment (DariusIMP) [reply zenoh-kotlin/src/commonTest/kotlin/io/zenoh/KeyExprTest.kt:58]: Yes, previously when the key expression was closed (meaning it wasn't bound anymore to a native keyexpr) then the equals operation returned false, since it was done at native level. Now, no matter if the key expression was closed, the equals is done by comparing the string representation of the key expression, that is a constant value associated to the keyexpr object.

File: zenoh-jni/src/key_expr.rs [hunk 13]
```diff
@@ -53,96 +49,63 @@ pub(crate) unsafe extern "C" fn Java_io_zenoh_jni_JNIKeyExpr_00024Companion_auto
...
+            let _ = err.throw_on_jvm(&mut env);
+            JString::default().as_raw()
+        })
 }
 
 #[no_mangle]
 #[allow(non_snake_case)]
-pub(crate) unsafe extern "C" fn Java_io_zenoh_jni_JNIKeyExpr_intersectsViaJNI(
-    _env: JNIEnv,
+pub(crate) unsafe extern "C" fn Java_io_zenoh_jni_JNIKeyExpr_00024Companion_intersectsViaJNI(
```
[the remark this answers is not in the document]
Comment (DariusIMP) [reply zenoh-jni/src/key_expr.rs:67]: It represents the '$' character. You see, the descriptor of the Companion class, which can be obtained by runninng
`javap -s zenoh-kotlin.build.classes.kotlin.jvm.main.io.zenoh.jni.JNIKeyExpr` is `Lio/zenoh/jni/JNIKeyExpr$Companion;`, and 00024 represents the $ char.

File: zenoh-jni/src/key_expr.rs (hunk 3 above)
Comment (DariusIMP) [reply zenoh-jni/src/key_expr.rs:143]: It's a pending task (although low priority) to refactor the error handling code on zenoh-jni. I will consider this for the future.

File: zenoh-jni/src/key_expr.rs (hunk 4 above)
Comment (DariusIMP) [reply zenoh-jni/src/key_expr.rs:166]: Right.

File: zenoh-jni/src/key_expr.rs (hunk 5 above)
Comment (DariusIMP) [reply zenoh-jni/src/key_expr.rs:171]: This is for the case where we provide a valid pointer to a key expression (for cases of KeyExpr instances that were obtained through declaring the key expression from a session for optimization purposes).
In such cases, the pointer is stored in the Kotlin layer as a raw long, which is in reality an Arc pointing to the key expression. We need to keep it valid until the user undeclares the key expression, and we do so by keeping the Arc reference count to the key expression to at least 1. Here doing `std::mem::forget(key_expr)` is meant to stop Rust from collecting the Rust key expr once the function finishes (otherwise the reference count will eventually be 0 and the key expression instance will be cleared).
And since we want to provide the key expression associated to the pointer, we return an arc clone.
Is it clearer?

File: zenoh-jni/src/query.rs (hunk 7 above)
Comment (DariusIMP) [reply zenoh-jni/src/query.rs:90]: In this case I need to be able to stop the function in case of error (we throw an exception and stop the function), thus the match with the `return`.

File: zenoh-jni/src/reply.rs (hunk 9 above)
Comment (DariusIMP) [reply zenoh-jni/src/reply.rs:77]: Ack

File: zenoh-jni/src/query.rs [hunk 14]
```diff
@@ -74,12 +79,19 @@ pub(crate) unsafe extern "C" fn Java_io_zenoh_jni_JNIQuery_replySuccessViaJNI(
...
-    std::mem::forget(key_expr);
+    let key_expr = match process_kotlin_key_expr(&mut env, &key_expr_str, key_expr_ptr) {
+        Ok(key_expr) => key_expr,
+        Err(err) => {
+            if let Err(err) = err.throw_on_jvm(&mut env) {
+                tracing::error!("{}", err);
+            }
+            return;
+        }
+    };
```
Comment (Charles-Schleich) [inline zenoh-jni/src/query.rs:90]: i still think that there may be a better rust pattern for this. 
` Ok(key_expr) => key_expr,`

File: zenoh-jni/src/session.rs [hunk 15]
```diff
@@ -347,12 +365,21 @@ pub unsafe extern "C" fn Java_io_zenoh_jni_JNISession_declareSubscriberViaJNI(
...
+        key_expr_ptr,
+        key_expr_str,
+        session_ptr,
+        callback,
+        on_close,
+        reliability,
+    ) {
         Ok(subscriber_ptr) => subscriber_ptr,
         Err(err) => {
             _ = err.throw_on_jvm(&mut env).map_err(|err| {
```
Comment (Charles-Schleich) [inline zenoh-jni/src/session.rs:385]: nit: There May be a better pattern to write this, but its low prio.

**Review by Charles-Schleich — CHANGES_REQUESTED** [review]

File: zenoh-jni/src/session.rs (hunk 15 above)
Comment (DariusIMP) [reply zenoh-jni/src/session.rs:385]: This exception throwing logic could be centralised somewhere. However this would enter the scope of the error handling refactor I mentioned in another comment previously, to do when we have more bandwidth.

File: zenoh-jni/src/query.rs (hunk 14 above)
Comment (DariusIMP) [reply zenoh-jni/src/query.rs:90]: I don't see how, we need to break the execution of the function with the return after throwing an exception on the jvm.

**Comment by Charles-Schleich** [comment]
lgtm

**Review by Charles-Schleich — APPROVED** [review]
lgtm
